GLOBAL_LIST_INIT(slasher_sounds, list(
	SOUND_ATTACK = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_5.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_6.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_7.ogg'),
	SOUND_DEATH = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_death_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_death_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_death_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_death_4.ogg'),
	SOUND_PAIN = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_5.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_6.ogg'),
	SOUND_SHOUT = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_4.ogg'),
	SOUND_SHOUT_LONG = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_long_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_long_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_long_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_long_4.ogg'),
	SOUND_SPEECH = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_speech_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_speech_2.ogg')
))
